"""make project description nullable

Revision ID: 2456f4c3a470
Revises: 
Create Date: 2025-04-25 19:17:36.755924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2456f4c3a470'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('datasets', 'tags',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               existing_nullable=True, 
               postgresql_using="tags::json")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('datasets', 'tags',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True, 
               postgresql_using="tags::json")
    # ### end Alembic commands ###
