"""add tags to projects

Revision ID: fb80df70f927
Revises: 2456f4c3a470
Create Date: 2025-04-25 19:41:11.059729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb80df70f927'
down_revision: Union[str, None] = '2456f4c3a470'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('tags', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'tags')
    # ### end Alembic commands ###
