"""Add annotation settings to augmentations

Revision ID: 0aa0a2ba1b9d
Revises: fa5d52df27e9
Create Date: 2025-06-30 13:09:15.738335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0aa0a2ba1b9d'
down_revision: Union[str, None] = 'fa5d52df27e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('augmentations', sa.Column('transform_annotations', sa.Boolean(), nullable=True))
    op.add_column('augmentations', sa.Column('annotation_settings', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('augmentations', 'annotation_settings')
    op.drop_column('augmentations', 'transform_annotations')
    # ### end Alembic commands ###
