"""Add annotation_files table

Revision ID: 659a697eaea9
Revises: 0aa0a2ba1b9d
Create Date: 2025-08-07 10:20:10.620492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '659a697eaea9'
down_revision: Union[str, None] = '0aa0a2ba1b9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
